// Auto-generated by scripts/sync-cms-to-static.ts
// DO NOT EDIT MANUALLY — regenerowane przy każdym buildzie (prebuild).

export const STATIC_CMS_CONTENT = {
  "magazyn_site_settings": {
    "title": "Lumine Concept",
    "description": "Produkty z plexi dla salonów beauty — logo 3D, cenniki, tabliczki i ramki na certyfikaty. Branding, który podnosi wartość Twojego salonu.",
    "announcementBar": {
      "enabled": true,
      "text": "Zamówienie express | Realizacja 72H +50% ceny"
    },
    "trustBar": {
      "followers": "27 000+",
      "realizations": "6 000+",
      "shippingLabel": "Realizacja ok. 10 dni roboczych"
    },
    "checkoutCallout": {
      "enabled": true,
      "title": "UWAGA",
      "message": "Nie ingerujemy w przesłany tekst. Prosimy o dokładne sprawdzenie poprawności treści.",
      "confirmLabel": "Rozumiem, kontynuuj"
    },
    "socialLinks": {
      "instagram": "https://www.instagram.com/lumine.concept/",
      "facebook": "https://www.facebook.com/profile.php?id=100063769314849"
    },
    "seo": {
      "metaTitle": "Branding salonu beauty z plexi — logo 3D i tabliczki",
      "metaDescription": "Logo 3D, cenniki, tabliczki i certyfikaty z plexi — branding, który podnosi wartość Twojego salonu beauty.",
      "ogTitle": "Branding salonu beauty z plexi",
      "ogDescription": "Logo 3D, cenniki i tabliczki, które sprawiają, że klientki robią zdjęcia w Twoim salonie."
    },
    "titleTemplate": "%s | Lumine Concept"
  },
  "magazyn_page_content": {
    "home": {
      "hero": {
        "desktopImageUrl": "/images/cms/b2d4cb97-1781822394507-ttcvbv-ZdjecieNOWE-_1_.webp",
        "mobileImageUrl": "/images/cms/132f8d7d-1781545464582-74l6v6-IMG_6839.webp",
        "headline": "CONCEPT",
        "subtitle": "Wyróżnij swój salon",
        "description": "Tablice z logo, cenniki i oznaczenia z plexi",
        "ctaLabel": "Zobacz produkty",
        "ctaHref": "/sklep"
      },
      "about": {
        "sideCaption": "Zapoznaj się z nami",
        "introHeading": "O NAS",
        "introParagraphs": [
          "Lumine to marka tworzona przez dwie siostry, która powstała z potrzeby podnoszenia standardów estetyki w branży beauty.\nProjektujemy z wyczuciem i konsekwencją, dbając o spójność, detal i profesjonalny odbiór.\nPomagamy salonom budować wizerunek premium w praktyce: porządkować przestrzeń, czytelnie prowadzić klienta i wzmacniać pierwsze wrażenie."
        ],
        "introImageAlt": "Założycielki Lumine Concept przy wspólnej pracy nad projektem",
        "introLabel": "my",
        "missionParagraphs": [
          "Naszą misją jest podnosić doświadczenie klientów\nw salonach beauty poprzez dopracowane detale\ni spójną komunikację w przestrzeni.\nTworzymy rozwiązania, które pomagają budować zaufanie,\nporządek i profesjonalny odbiór marki —\nod wejścia, przez recepcję, aż po strefy zabiegowe.\nStawiamy na jakość, czytelność i estetykę,\nktóre realnie pracują na wizerunek salonu każdego dnia."
        ],
        "missionImageAlt": "Praca nad tablicą z logo w pracowni Lumine Concept",
        "missionLabel": "nasza misja",
        "closingImageAlt": "Gotowa tablica z logo salonu beauty — realizacja Lumine Concept"
      },
      "brandingCta": {
        "desktopBackgroundUrl": "/images/cms/e086ea83-1781216823694-0cxkhd-Monia2.webp"
      }
    },
    "logo-3d": {
      "hero": {
        "desktopImageUrl": "/images/cms/e66836a9-1781210588745-ssdzxx-tlo_strona_logo.webp",
        "mobileImageUrl": "/images/cms/ebcb886a-1781203043467-jq9uc7-Tablice.webp",
        "headline": "Tablica z logo",
        "description": "Logo Twojej marki zrealizowane w postaci kreatywnej ozdobnej tablicy, którą możesz zamieścić na ścianie",
        "ctaLabel": "Uzyskaj wycenę",
        "ctaHref": "#formularz",
        "ctaAriaLabel": "Przewiń do formularza — zamów tablicę z logo",
        "headlineUppercase": true,
        "ctaShowDownArrow": true
      },
      "gallery": [
        {
          "id": "g-3a35bb42",
          "imageUrl": "/images/cms/beab795d-1781552862220-a1gb11-IMG_1520.webp",
          "order": 1
        },
        {
          "id": "g-7ed6b477",
          "imageUrl": "/images/cms/3d75c4ef-1781552868370-9b4p8e-IMG_7601.webp",
          "order": 2
        },
        {
          "id": "g-dac879ac",
          "imageUrl": "/images/cms/03c47232-1781552875203-ub35u7-IMG_4548.webp",
          "order": 3
        },
        {
          "id": "g-f5209912",
          "imageUrl": "/images/cms/18787cd4-1781552880336-t9s0si-IMG_6545.webp",
          "order": 4
        },
        {
          "id": "g-8ae69896",
          "imageUrl": "/images/cms/6ee4f5b2-1781553540330-r89nbz-IMG_0254.webp",
          "order": 4
        },
        {
          "id": "g-c1841616",
          "imageUrl": "/images/cms/ce1d47f6-1781553547696-lsnimy-IMG_0749.webp",
          "order": 5
        },
        {
          "id": "g-332cfba7",
          "imageUrl": "/images/cms/f5dd2f09-1781553552775-8klezw-IMG_0760.webp",
          "order": 6
        },
        {
          "id": "g-7be84c37",
          "imageUrl": "/images/cms/301759f4-1781553563703-tp0fvk-IMG_1483.webp",
          "order": 7
        }
      ]
    },
    "shop": {
      "categoryTiles": [
        {
          "title": "Gotowe wzory",
          "cta": "PRZEGLĄDAJ WZORY",
          "href": "/sklep/gotowe-wzory",
          "imageUrl": "/images/categories/gotowe-wzory-personel.webp"
        },
        {
          "title": "Tablice z logo",
          "cta": "Uzyskaj wycenę",
          "href": "/sklep/tablice-z-logo",
          "imageUrl": "/images/categories/logo-kategoria-nail-boss.webp"
        },
        {
          "title": "Certyfikaty",
          "cta": "Zobacz certyfikaty",
          "href": "/sklep/certyfikaty",
          "imageUrl": "/images/categories/certyfikat-kategoria.png"
        }
      ]
    },
    "o-nas": {
      "hero": {
        "desktopImageUrl": "/images/cms/69c0352d-1781623312197-rh6cr6-IMG_2448.webp",
        "mobileImageUrl": "https://medusa-backend-lumineconceptpl.up.railway.app/static/1781611453841-B79595B2-5BE1-4C3F-BC00-383EF9E4A4DA%20(1).webp",
        "headline": "O NAS",
        "subtitle": "Kim jesteśmy?",
        "description": " ",
        "ctaLabel": "Sklep",
        "ctaHref": "/sklep"
      },
      "about": {
        "sideCaption": "Zapoznaj się z nami",
        "introHeading": "O NAS",
        "introParagraphs": [
          "Lumine to marka tworzona przez dwie siostry,\nktóra powstała z potrzeby podnoszenia\nstandardów estetyki w branży beauty.\nProjektujemy z wyczuciem i konsekwencją,\ndbając o spójność, detal i profesjonalny odbiór.\nPomagamy salonom budować wizerunek premium w praktyce:\nporządkować przestrzeń, czytelnie prowadzić klienta\ni wzmacniać pierwsze wrażenie."
        ],
        "introImageUrl": "/images/cms/d785699e-1781623323773-k5ef5x-KasiaMonia.webp",
        "introImageAlt": "Założycielki Lumine Concept przy wspólnej pracy nad projektem",
        "introLabel": "my",
        "missionParagraphs": [
          "Naszą misją jest podnosić doświadczenie klientów\nw salonach beauty poprzez dopracowane detale\ni spójną komunikację w przestrzeni.\nTworzymy rozwiązania, które pomagają budować zaufanie,\nporządek i profesjonalny odbiór marki -\nod wejścia, przez recepcję, aż po strefy zabiegowe.\nStawiamy na jakość, czytelność i estetykę,\nktóre realnie pracują na wizerunek salonu każdego dnia."
        ],
        "missionImageUrl": "/images/cms/e4789e1c-1781623327583-hipyzc-Monia1.webp",
        "missionImageAlt": "Praca nad tablicą z logo w pracowni Lumine Concept",
        "missionLabel": "nasza misja",
        "closingParagraphs": [
          "Tworzymy dla marek beauty, które\nchcą rosnąć w sposób spójny i świadomy.\nDla salonów, które myślą o wizerunku długofalowo\ni wybierają rozwiązania dopasowane do stylu miejsca.\nJeśli bliskie jest Ci podejście „mniej, ale lepiej”\n- jesteś w dobrym miejscu."
        ],
        "closingImageUrl": "https://medusa-backend-lumineconceptpl.up.railway.app/static/1781630669040-Monia2-_1_.webp",
        "closingImageAlt": "Gotowa tablica z logo salonu beauty — realizacja Lumine Concept",
        "closingLabel": "dla kogo tworzymy?"
      }
    }
  },
  "magazyn_global_content": {
    "salonLogos": [
      {
        "id": "fallback-1",
        "name": "Sabrija Store",
        "logoUrl": "/images/logos/sabrija-store.png",
        "order": 0
      }
    ],
    "instagramTiles": [
      {
        "id": "ig-5493ab44",
        "postUrl": "https://www.instagram.com/reel/DZfjG1qAI41/?igsh=MXkweWM0NWRldmZiYQ==",
        "imageUrl": "/images/cms/aeb9202a-1781782463239-b3rrbo-E45CB9DD-E716-44BB-B65F-2E25B13F071F.webp"
      },
      {
        "id": "ig-b868dfa4",
        "postUrl": "https://www.instagram.com/reel/DZVRhX8hmjc/?igsh=MWRtZXk4dXZobmQ3eA==",
        "imageUrl": "/images/cms/0be43eef-1781452179306-g6c73d-Zrzut_ekranu_2026-06-14_o_17.49.05.webp"
      },
      {
        "id": "ig-183da094",
        "postUrl": "https://www.instagram.com/p/DZDMnlKSURd/",
        "imageUrl": "/images/cms/fb65d93d-1781452486738-xe3cz0-Zrzut_ekranu_2026-06-14_o_17.54.37.webp"
      },
      {
        "id": "ig-2d184698",
        "postUrl": "https://www.instagram.com/p/DZK9uISph6Q/",
        "imageUrl": "/images/cms/d1d5f462-1781452447037-im6tgn-Zrzut_ekranu_2026-06-14_o_17.53.51.webp"
      },
      {
        "id": "ig-9d9f6fd3",
        "postUrl": "https://www.instagram.com/p/DY43kYPBj3X/",
        "imageUrl": "/images/cms/b033f246-1781452522519-mbcp9z-Zrzut_ekranu_2026-06-14_o_17.55.10.webp"
      },
      {
        "id": "ig-7ee6853c",
        "postUrl": "https://www.instagram.com/p/DYxJhZnsfQ9/",
        "imageUrl": "/images/cms/cb560e7e-1781452568674-dt6f0u-Zrzut_ekranu_2026-06-14_o_17.55.55.webp"
      }
    ]
  }
} as const;

export type StaticCmsContent = typeof STATIC_CMS_CONTENT;
