// Auto-generated by sync-cms-to-static.ts
// This file will be created during build - fallback export for dev

export const STATIC_CMS_CONTENT = {
	magazyn_site_settings: {},
	magazyn_page_content: {},
	magazyn_global_content: {},
} as const;

export type StaticCmsContent = typeof STATIC_CMS_CONTENT;
