#!/usr/bin/env tsx
/**
 * Sync CMS content → static files przed buildem.
 * Ściąga wszystkie obrazy i content z Medusa do /public i generuje static TS.
 */

import fs from "node:fs";
import path from "node:path";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";

const MEDUSA_URL = process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL || "http://localhost:9000";
const ADMIN_EMAIL = process.env.MEDUSA_ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.MEDUSA_ADMIN_PASSWORD;

const PUBLIC_DIR = path.join(process.cwd(), "public");
const CMS_IMAGES_DIR = path.join(PUBLIC_DIR, "images", "cms");
const STATIC_CONTENT_FILE = path.join(process.cwd(), "lib", "content", "static-cms-content.ts");

type StoreMetadata = {
	magazyn_site_settings?: Record<string, unknown>;
	magazyn_page_content?: Record<string, unknown>;
	magazyn_global_content?: Record<string, unknown>;
};

async function getAdminToken(): Promise<string> {
	if (!ADMIN_EMAIL || !ADMIN_PASSWORD) {
		throw new Error("MEDUSA_ADMIN_EMAIL and MEDUSA_ADMIN_PASSWORD required");
	}

	const res = await fetch(`${MEDUSA_URL}/admin/auth`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ email: ADMIN_EMAIL, password: ADMIN_PASSWORD }),
	});

	if (!res.ok) {
		throw new Error(`Auth failed: ${res.status}`);
	}

	const data = await res.json();
	return data.user?.api_token;
}

async function fetchStoreMetadata(token: string): Promise<StoreMetadata> {
	const res = await fetch(`${MEDUSA_URL}/admin/store`, {
		headers: { Authorization: `Bearer ${token}` },
	});

	if (!res.ok) {
		throw new Error(`Store fetch failed: ${res.status}`);
	}

	const data = await res.json();
	return data.store?.metadata || {};
}

async function downloadImage(url: string, filename: string): Promise<string> {
	console.log(`  → ${filename}`);
	
	const res = await fetch(url);
	if (!res.ok || !res.body) {
		console.warn(`    ⚠ Failed to download ${url}`);
		return url; // Fallback to original URL
	}

	const filepath = path.join(CMS_IMAGES_DIR, filename);
	const fileStream = fs.createWriteStream(filepath);
	
	await pipeline(Readable.fromWeb(res.body as any), fileStream);
	
	return `/images/cms/${filename}`;
}

function extractImageUrls(obj: any): string[] {
	const urls: string[] = [];
	
	function traverse(val: any) {
		if (typeof val === "string" && (val.startsWith("http") || val.startsWith("/"))) {
			if (val.match(/\.(jpg|jpeg|png|webp|gif)$/i)) {
				urls.push(val);
			}
		} else if (Array.isArray(val)) {
			val.forEach(traverse);
		} else if (val && typeof val === "object") {
			Object.values(val).forEach(traverse);
		}
	}
	
	traverse(obj);
	return [...new Set(urls)];
}

async function downloadAllImages(metadata: StoreMetadata): Promise<Map<string, string>> {
	console.log("\n📦 Downloading CMS images...");
	
	fs.mkdirSync(CMS_IMAGES_DIR, { recursive: true });
	
	const imageUrls = extractImageUrls(metadata);
	console.log(`Found ${imageUrls.length} images`);
	
	const urlMap = new Map<string, string>();
	
	for (const url of imageUrls) {
		const filename = path.basename(new URL(url, "http://localhost").pathname);
		const localPath = await downloadImage(url, filename);
		urlMap.set(url, localPath);
	}
	
	return urlMap;
}

function replaceImageUrls(obj: any, urlMap: Map<string, string>): any {
	if (typeof obj === "string") {
		return urlMap.get(obj) || obj;
	}
	if (Array.isArray(obj)) {
		return obj.map(item => replaceImageUrls(item, urlMap));
	}
	if (obj && typeof obj === "object") {
		const result: any = {};
		for (const [key, val] of Object.entries(obj)) {
			result[key] = replaceImageUrls(val, urlMap);
		}
		return result;
	}
	return obj;
}

function generateStaticContentFile(metadata: StoreMetadata, urlMap: Map<string, string>) {
	console.log("\n📝 Generating static content file...");
	
	const localizedMetadata = replaceImageUrls(metadata, urlMap);
	
	const content = `// Auto-generated by sync-cms-to-static.ts
// DO NOT EDIT MANUALLY - changes will be overwritten on next build

export const STATIC_CMS_CONTENT = ${JSON.stringify(localizedMetadata, null, 2)} as const;

export type StaticCmsContent = typeof STATIC_CMS_CONTENT;
`;
	
	fs.writeFileSync(STATIC_CONTENT_FILE, content, "utf-8");
	console.log(`✓ Written to ${path.relative(process.cwd(), STATIC_CONTENT_FILE)}`);
}

async function main() {
	console.log("🚀 Syncing CMS content to static files...\n");
	
	try {
		console.log("🔐 Authenticating...");
		const token = await getAdminToken();
		console.log("✓ Authenticated\n");
		
		console.log("📚 Fetching CMS content...");
		const metadata = await fetchStoreMetadata(token);
		console.log("✓ Fetched\n");
		
		const urlMap = await downloadAllImages(metadata);
		
		generateStaticContentFile(metadata, urlMap);
		
		console.log("\n✨ Sync complete! CMS content is now static.");
		console.log(`   ${urlMap.size} images localized`);
		console.log(`   PageSpeed ready 🚀\n`);
	} catch (error) {
		console.error("\n❌ Sync failed:", error);
		process.exit(1);
	}
}

main();
